[build-system]
requires = [
    "hatchling==1.32.0",
    "hatch-vcs==0.5.0",
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/faststream_celery/_version.py"

[project]
name = "faststream-celery"
dynamic = ["version"]
description = "Faststream Celery (kumbu) broker"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]

authors = [
    { name = "Danil Kovalev", email = "dan.kovalev2013@gmail.com" },
]

classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

requires-python = ">=3.10"

dependencies = [
    "faststream>=0.7.5",
    "kombu>=5.3,<6",
]

[project.urls]
Source = "https://github.com/C3EQUALZz/faststream-celery"
Homepage = "https://github.com/C3EQUALZz/faststream-celery"
Tracker = "https://github.com/C3EQUALZz/faststream-celery/issues"

[dependency-groups]
dev = [
    {include-group = "lint"},
    {include-group = "test"},
    "prek>=0.2.5",
]
lint = [
    "bandit>=1.8.6",
    "celery-types>=0.26.0",
    "codespell>=2.4.1",
    "mypy>=1.18.2",
    "ruff>=0.14.0",
    "semgrep>=1.139.0",
    "zizmor>=1.14.2",
]
test = [
    "celery>=5.4.0",
    "redis>=5.0.0",
    "nox>=2025.5.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-cov>=7.0.0",
    "testcontainers>=4.15.0",
]

[tool.bandit]
skips = ["B101"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"
asyncio_default_test_loop_scope = "function"
addopts = "-m 'not slow and not connected' --strict-markers"
markers = [
    "slow: slow tests",
    "connected: tests requiring a real broker over the network",
    "rabbit: RabbitMQ broker tests",
    "redis: Redis broker tests",
    "all: the full test suite",
]
